# Generated by Django 5.2.9 on 2025-12-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_spotify',
        ),
    ]
