# Generated by Django 5.2.9 on 2025-12-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_followings_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follower',
        ),
    ]
