# Generated by Django 5.2.9 on 2025-12-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_followers_user_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='followers',
        ),
    ]
