# Generated by Django 5.2.9 on 2025-12-21 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_id', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message='Spotify ID must be exactly 22 characters.', regex='^[A-Za-z0-9]{22}$')])),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.PositiveSmallIntegerField(null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spotify_id', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator(message='Spotify ID must be exactly 22 characters.', regex='^[A-Za-z0-9]{22}$')])),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.PositiveSmallIntegerField(null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('artists', models.ManyToManyField(related_name='tracks', to='musics.artist')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='audio_features', serialize=False, to='musics.track')),
                ('acousticness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('danceability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('instrumentalness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('key', models.SmallIntegerField(choices=[(-1, 'unknown'), (0, 'C'), (1, 'C♯/D♭'), (2, 'D'), (3, 'D♯/E♭'), (4, 'E'), (5, 'F'), (6, 'F♯/G♭'), (7, 'G'), (8, 'G♯/A♭'), (9, 'A'), (10, 'A♯/B♭'), (11, 'B')], null=True)),
                ('liveness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('loudness', models.FloatField(validators=[django.core.validators.MinValueValidator(-60.0), django.core.validators.MaxValueValidator(0.0)])),
                ('mode', models.BooleanField(help_text='True=major, False=minor', null=True)),
                ('speechiness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tempo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(300.0)])),
                ('valence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_index', models.PositiveIntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.track')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='musics.PlaylistTrack', to='musics.track'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user', 'name')},
        ),
    ]
