# Generated by Django 5.2.9 on 2025-12-22 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set(),
        ),
    ]
