# Generated by Django 5.2.9 on 2025-12-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_playlisttrack_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', through='musics.PlaylistTrack', to='musics.track'),
        ),
    ]
