# Generated by Django 5.2.9 on 2025-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='musics.PlaylistTrack', to='musics.track'),
        ),
    ]
