# Generated by Django 5.2.9 on 2025-12-25 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_alter_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofeatures',
            name='acousticness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='danceability',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='energy',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='instrumentalness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='liveness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='loudness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-60.0), django.core.validators.MaxValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='speechiness',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='tempo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(300.0)]),
        ),
        migrations.AlterField(
            model_name='audiofeatures',
            name='valence',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
