# Generated by Django 5.2.9 on 2025-12-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(max_length=660),
        ),
    ]
