# Generated by Django 5.2.9 on 2025-12-25 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_alter_thread_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threadrecommend',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='threadrecommend',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadrecommend',
            name='user',
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='like_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentRecommend',
        ),
        migrations.DeleteModel(
            name='ThreadRecommend',
        ),
    ]
